name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Select the version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - none
          - patch
          - minor
          - major

jobs:
  prepare_release:
    runs-on: windows-latest
    outputs:
      app_version: ${{ steps.get_version.outputs.APP_VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          architecture: x64

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r requirements.txt --upgrade

      - name: Bump Version
        id: bump_version
        if: github.event.inputs.version_bump != 'none'
        run: |
          new_version=$(python bump_version.py ${{ github.event.inputs.version_bump }})
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/utils/version.py
          git commit -m "Bump version to $new_version"
          git push origin HEAD:${GITHUB_REF}
          echo "APP_VERSION=$new_version" >> $GITHUB_OUTPUT
        shell: bash

      - name: Get Version (if no bump)
        id: get_version
        if: github.event.inputs.version_bump == 'none'
        run: |
          version=$(python -c "from src.utils.version import APP_VERSION; print(APP_VERSION)")
          echo "APP_VERSION=$version" >> $GITHUB_OUTPUT
        shell: bash

      - name: Save code for build
        uses: actions/upload-artifact@v3
        with:
          name: source-code
          path: .

  build:
    runs-on: ${{ matrix.os }}
    needs: prepare_release
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Download source code
        uses: actions/download-artifact@v3
        with:
          name: source-code

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          architecture: x64

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python -m pip install -r requirements.txt --upgrade

      - name: Bundle application (Windows)
        if: runner.os == 'Windows'
        run: powershell -ExecutionPolicy Bypass -File .\bundle_app_windows.ps1
        shell: pwsh

      - name: Bundle application (macOS)
        if: runner.os == 'macOS'
        run: bash ./bundle_app_macos.sh
        shell: bash

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.prepare_release.outputs.app_version }}
          files: ./dist/NITools_${{ runner.os }}_v${{ needs.prepare_release.outputs.app_version }}.zip
          name: Release v${{ needs.prepare_release.outputs.app_version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
